#Count number of nucleotides in a string

def count_nucleotides(s):
    base_count = {'A':0,'C':0,'G':0,'T':0}
    for base in s:
        if base == 'A':
            base_count['A'] += 1
        if base == 'C':
            base_count['C'] += 1
        if base == 'G':
            base_count['G'] += 1
        if base == 'T':
            base_count['T'] += 1
    for nucleotide,count in base_count.items():
        print(f"{nucleotide}: {count}")

count_nucleotides('TGTCAATTGCATTGTGCGGTCAAGCTACTATGTTGAGGTGAGCTCTACGGGGTTGTTCCTGGAATTTTGCCGCGTGACCCAAAGTATTGCAGTCTGCGACGGGAAAAAGAATGTCCAATTATTTGCCCCCGCGATCCTATCCGTCAGTCTCTAATGTGGTGCTACGTACCCAGTCTTAAGCGTCAGCAATGTGATGATGCCATACAGAGTACATGATTGTATATTGCCTAGCGATATCGATGACAGGGGTCTTCTGATACTTGAGCACAGACAAAAGCATGCTATGGCCAGAAGTGTTCCAGCTCAACCAGAGGGTTACTTGCCTTGTATTCGTTGCTATGCCGAACACTAGCAAGGTACAGGGATCCACATCTCTTCCCAACCATGTGCAAACAGAAAAATTTAAGGATGATATATATAGGCGCCATTAAGTCACATGGTGGTAGCGCATCAGCCTCGCCTCCGCACGGACCATTAACCCCATTACATCTAACGGCCCAAGGTGGTACGCGTAAACCCTCAGGGTAGGATTGGTCGAGTCCCTCGGCCTGCTGGAGGACGATAATATCCGGATACGTGGTCACAGGCCCCATTAGACAAAGTGGCGATCGTACCGCGTAACAAACCTCGTGATCGAGAGCGCGTTACTCAGAGGTCATTCAACTTCCGTCATAAGGGCAGCTCCGCCGAGGTGGGTCATCGCTTTGAGAGAAGGCCGGCGAACTCACACATCGTAGCGGCCTCGTAGTCCGGTGGGCTATAAAGGTGTTTAGGGCCTGTGCGAGACTCGCTAGTAGGCCCCACGCGGAGACTCCTTGATCTCTCGTTTATCGCTGTCGTAAGGAACGCTTGTGATCGGGTTCACATGCACCTCTGCATAAGTTTGTAGTTCATCGAGAACAGTATATT')